[package]
name = "ast_from_path"
version = "0.1.0"
edition = "2018"

# [lib]
# proc-macro = true

[dependencies]
syn = { version = "2.0.53", features = ["full", "visit", "extra-traits"] }
quote = "1.0"
regex = "1.5"
proc-macro2 = "1.0.79"